acr_name: "acrjorengap.azurecr.io"  # URL de tu registro de contenedores en Azure
image_name: "nginx-web"            # nombre que tendrá tu imagen Docker
image_tag: "casopractico2"                # versión/tag de la imagen
container_name: "webserver"        # nombre del contenedor cuando se ejecute en Podman
http_user: "admin"                 # usuario para autenticación básica (htpasswd)
http_password: "admin"             # contraseña para ese usuario
cert_country: "ES"                 # país para el certificado x.509
cert_org: "cp2"                    # organización para el certificado x.509
cert_domain: "miservidor.local"    # dominio para el certificado x.509