---
- name: Desplegar servidor web Nginx en Podman
  hosts: vm
  become: true
  roles:
    - webserver

- name: Desplegar Apache en AKS
  hosts: k8s
  connection: local
  become: false
  roles:
    - kubernetes